default_chain: STRIDE-TESTNET-2
chains:
  GAIA:
    key: gaia-icq
    chain-id: GAIA
    rpc-addr: http://localhost:26657
    grpc-addr: http://localhost:26090
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 1uatom
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
    memo-prefix: gacon#2074
  STRIDE-TESTNET-2:
    key: strided-icq
    chain-id: STRIDE-TESTNET-2
    rpc-addr: http://localhost:16657
    grpc-addr: http://localhost:16090
    account-prefix: stride
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 1ustrd
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
    memo-prefix: gacon#2074
cl: {}
